name: Django Group CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies and Run Pylint
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          
          # Install project dependencies
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          pip install django  # Explicitly install Django as a failsafe
          
          # Install linter
          pip install pylint
          
          # Run Pylint
          echo "Running Pylint..."
          pylint $(git ls-files "*.py")

  test:
    needs: [lint]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies and Run Django tests
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip

          # Install project dependencies and testing tools
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          pip install django  # Explicitly install Django as a failsafe
          pip install coverage pytest

          # Run Django tests
          echo "Running Django tests..."
          coverage run -m pytest
        continue-on-error: true

      - name: Show coverage report
        if: always()
        run: |
          source venv/bin/activate
          coverage report -m

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate deployment
        run: |
          echo "Deploying to production..."
          # Add your real deployment commands here if needed